name: GitHub Actions Demo
on: [push]
jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node14-2-${{ hashFiles('**/package-lock.json') }}
      - name: Install npm 7 # https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
        run: npm install -g npm@7
      - name: Install npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

  run-web:
    needs: npm-install
    runs-on: ubuntu-latest
    defaults:
       run:
          shell: bash
          working-directory: ./web
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node14-2-${{ hashFiles('**/package-lock.json') }}
      - name: List files in the repository
        run: |
          ls && cat index.js 
      - name: Run program
        run: |
          node index.js

  run-api:
    needs: npm-install
    runs-on: ubuntu-latest
    defaults:
       run:
          shell: bash
          working-directory: ./api
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node14-2-${{ hashFiles('**/package-lock.json') }}
      - name: List files in the repository
        run: |
          ls && cat index.js 
      - name: Run program
        run: |
          node index.js
