name: GitHub Actions Demo
on: [push]
jobs:
  npm-install-web:
    defaults:
       run:
          shell: bash
          working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: npm-cache-web
        with:
          path: './web/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./web/package-lock.json') }}
      - name: Install npm
        if: steps.npm-cache-web.outputs.cache-hit != 'true'
        run: npm install

  npm-install-api:
    defaults:
       run:
          shell: bash
          working-directory: ./api
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: npm-cache-api
        with:
          path: './api/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
      - name: Install npm
        if: steps.npm-cache-api.outputs.cache-hit != 'true'
        run: npm install

  run-both:
    needs: 
      - npm-install-web
      - npm-install-api
    runs-on: ubuntu-latest
    defaults:
       run:
          shell: bash
          working-directory: ./web
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: npm-cache-web
        with:
          path: './web/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./web/package-lock.json') }}
      - uses: actions/cache@v2
        id: npm-cache-api
        with:
          path: './api/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
      - name: Run web first, then API
        run: |
          node index.js && cd ../api/ && node index.js
